import { useEffect, useState } from "react";
import { KeyRound, Loader2, Plus, Save, Trash2, UserRound } from "lucide-react";
import { ErrorState, Skeleton, useToast } from "../components/ui";
import { formatDate, formatRelative } from "../lib/format";
import { ADMIN_PATH } from "../lib/config";
import { useAuditLog, useSaveSettings, useSettings } from "../lib/queries";
import type { Settings } from "../lib/types";
import { AdminPanel, ImageField, PageHeading } from "./components";
import { useAuth, useChangePassword, useUpdateProfile } from "./auth";

// Everything a visitor reads outside product pages lives here: brand copy,
// footer columns, SEO defaults and the public feature toggles.
export function SettingsAdmin() {
  const { data, isLoading, error, refetch } = useSettings();
  const save = useSaveSettings();
  const toast = useToast();
  const [draft, setDraft] = useState<Settings | null>(null);

  useEffect(() => {
    if (data) setDraft(structuredClone(data));
  }, [data]);

  if (isLoading || !draft) return <div className="dashboard"><Skeleton height={300} /></div>;
  if (error) return <div className="dashboard"><ErrorState error={error} onRetry={() => refetch()} /></div>;

  const saveGroup = async (key: keyof Settings) => {
    try {
      await save.mutateAsync({ key, value: draft[key] as unknown as Record<string, unknown> });
      toast("Settings saved");
    } catch (saveError) {
      toast(saveError instanceof Error ? saveError.message : "Save failed", "error");
    }
  };

  const saveAll = async () => {
    for (const key of ["site", "seo", "footer", "features"] as (keyof Settings)[]) {
      await save.mutateAsync({ key, value: draft[key] as unknown as Record<string, unknown> });
    }
    toast("All settings saved");
  };

  return (
    <div className="dashboard">
      <PageHeading title="Settings" text="Brand, SEO defaults, footer and public feature toggles.">
        <button type="button" className="btn primary" onClick={saveAll} disabled={save.isPending}>
          {save.isPending ? <Loader2 size={15} className="spin" /> : <Save size={15} />} Save all
        </button>
      </PageHeading>

      <AdminPanel
        title="Site"
        subtitle="Brand name and shared copy"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("site")}>Save</button>}
      >
        <div className="form-grid">
          <label>Site name<input value={draft.site.name} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, name: event.target.value } })} /></label>
          <label>Tagline<input value={draft.site.tagline} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, tagline: event.target.value } })} /></label>
          <label>Support email<input value={draft.site.supportEmail} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, supportEmail: event.target.value } })} /></label>
          <label>Search placeholder<input value={draft.site.searchPlaceholder} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, searchPlaceholder: event.target.value } })} /></label>
        </div>
      </AdminPanel>

      <AdminPanel
        title="SEO defaults"
        subtitle="Used when a page or product has no override"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("seo")}>Save</button>}
      >
        <div className="form-grid">
          <label>Title template<input value={draft.seo.titleTemplate} onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, titleTemplate: event.target.value } })} placeholder="%s — ToolHub" /></label>
          <label>Default title<input value={draft.seo.defaultTitle} onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, defaultTitle: event.target.value } })} /></label>
          <label className="wide">
            Default description
            <textarea rows={2} value={draft.seo.defaultDescription} onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, defaultDescription: event.target.value } })} />
          </label>
          <label className="wide">
            Keywords
            <input
              value={draft.seo.keywords.join(", ")}
              onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, keywords: event.target.value.split(",").map((word) => word.trim()).filter(Boolean) } })}
            />
          </label>
          <div className="wide">
            <ImageField
              label="Default OpenGraph image"
              prefix="branding"
              value={draft.seo.ogImage}
              onChange={(url) => setDraft({ ...draft, seo: { ...draft.seo, ogImage: url } })}
            />
          </div>
        </div>
        <p className="form-note">
          sitemap.xml and robots.txt are generated by the server. robots.txt disallows <code>{ADMIN_PATH}</code>, and the panel is
          served with a noindex header.
        </p>
      </AdminPanel>

      <AdminPanel
        title="Footer"
        subtitle="Columns, links and newsletter copy"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("footer")}>Save</button>}
      >
        <div className="form-grid">
          <label className="wide">
            About text
            <textarea rows={2} value={draft.footer.about} onChange={(event) => setDraft({ ...draft, footer: { ...draft.footer, about: event.target.value } })} />
          </label>
          <label className="wide">Copyright<input value={draft.footer.copyright} onChange={(event) => setDraft({ ...draft, footer: { ...draft.footer, copyright: event.target.value } })} /></label>
        </div>

        {draft.footer.columns.map((column, columnIndex) => (
          <div className="footer-column-editor" key={columnIndex}>
            <div className="repeater-row">
              <input
                className="grow"
                value={column.title}
                placeholder="Column title"
                onChange={(event) => {
                  const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, title: event.target.value } : item));
                  setDraft({ ...draft, footer: { ...draft.footer, columns } });
                }}
              />
              <button
                type="button"
                className="icon-btn danger"
                onClick={() => setDraft({ ...draft, footer: { ...draft.footer, columns: draft.footer.columns.filter((_, i) => i !== columnIndex) } })}
                aria-label="Remove column"
              >
                <Trash2 size={13} />
              </button>
            </div>
            {column.links.map((link, linkIndex) => (
              <div className="repeater-row indented" key={linkIndex}>
                <input
                  value={link.label}
                  placeholder="Label"
                  onChange={(event) => {
                    const links = column.links.map((item, i) => (i === linkIndex ? { ...item, label: event.target.value } : item));
                    const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, links } : item));
                    setDraft({ ...draft, footer: { ...draft.footer, columns } });
                  }}
                />
                <input
                  value={link.href}
                  placeholder="/path"
                  onChange={(event) => {
                    const links = column.links.map((item, i) => (i === linkIndex ? { ...item, href: event.target.value } : item));
                    const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, links } : item));
                    setDraft({ ...draft, footer: { ...draft.footer, columns } });
                  }}
                />
                <button
                  type="button"
                  className="icon-btn danger"
                  onClick={() => {
                    const links = column.links.filter((_, i) => i !== linkIndex);
                    const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, links } : item));
                    setDraft({ ...draft, footer: { ...draft.footer, columns } });
                  }}
                  aria-label="Remove link"
                >
                  <Trash2 size={13} />
                </button>
              </div>
            ))}
            <button
              type="button"
              className="btn ghost small"
              onClick={() => {
                const columns = draft.footer.columns.map((item, i) =>
                  i === columnIndex ? { ...item, links: [...item.links, { label: "", href: "/" }] } : item
                );
                setDraft({ ...draft, footer: { ...draft.footer, columns } });
              }}
            >
              <Plus size={13} /> Add link
            </button>
          </div>
        ))}

        <button
          type="button"
          className="btn ghost small"
          onClick={() => setDraft({ ...draft, footer: { ...draft.footer, columns: [...draft.footer.columns, { title: "New column", links: [] }] } })}
        >
          <Plus size={13} /> Add column
        </button>
      </AdminPanel>

      <AccountPanel />

      <AdminPanel
        title="Public features"
        subtitle="Turn parts of the site on or off"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("features")}>Save</button>}
      >
        <div className="switch-row">
          <label className="switch">
            <input
              type="checkbox"
              checked={draft.features.reviewsEnabled}
              onChange={(event) => setDraft({ ...draft, features: { ...draft.features, reviewsEnabled: event.target.checked } })}
            />
            Visitor reviews
          </label>
          <label className="switch">
            <input
              type="checkbox"
              checked={draft.features.newsletterEnabled}
              onChange={(event) => setDraft({ ...draft, features: { ...draft.features, newsletterEnabled: event.target.checked } })}
            />
            Newsletter form
          </label>
          <label className="switch">
            <input
              type="checkbox"
              checked={draft.features.showDownloadCounts}
              onChange={(event) => setDraft({ ...draft, features: { ...draft.features, showDownloadCounts: event.target.checked } })}
            />
            Show download counts
          </label>
        </div>
      </AdminPanel>

      <ActivityPanel />
    </div>
  );
}

// The panel has one administrator, so the account lives here rather than in a
// staff section: rename it, change the sign-in email, change the password.
function AccountPanel() {
  const { user } = useAuth();
  const updateProfile = useUpdateProfile();
  const changePassword = useChangePassword();
  const toast = useToast();

  const [name, setName] = useState(user?.name ?? "");
  const [email, setEmail] = useState(user?.email ?? "");
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [repeatPassword, setRepeatPassword] = useState("");

  const saveProfile = async () => {
    try {
      await updateProfile.mutateAsync({ name, email });
      toast("Account updated");
    } catch (error) {
      toast(error instanceof Error ? error.message : "Could not update the account", "error");
    }
  };

  const savePassword = async () => {
    if (newPassword !== repeatPassword) {
      toast("The new passwords do not match", "error");
      return;
    }
    try {
      await changePassword.mutateAsync({ currentPassword, newPassword });
      setCurrentPassword("");
      setNewPassword("");
      setRepeatPassword("");
      toast("Password changed");
    } catch (error) {
      toast(error instanceof Error ? error.message : "Could not change the password", "error");
    }
  };

  return (
    <>
      <AdminPanel
        title="Administrator account"
        subtitle="The only account that can sign in to this panel"
        action={
          <button type="button" className="btn ghost small" onClick={saveProfile} disabled={updateProfile.isPending}>
            <UserRound size={13} /> Save
          </button>
        }
      >
        <div className="form-grid">
          <label>Name<input value={name} onChange={(event) => setName(event.target.value)} /></label>
          <label>Sign-in email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label>
        </div>
        <p className="form-note">
          Last sign in: {user?.lastLoginAt ? `${formatRelative(user.lastLoginAt)} (${formatDate(user.lastLoginAt)})` : "never"}.
          There is no staff management and no visitor accounts: this is the only login in the whole system.
        </p>
      </AdminPanel>

      <AdminPanel
        title="Password"
        subtitle="Change the sign-in password"
        action={
          <button
            type="button"
            className="btn ghost small"
            onClick={savePassword}
            disabled={changePassword.isPending || !currentPassword || newPassword.length < 10}
          >
            <KeyRound size={13} /> Change
          </button>
        }
      >
        <div className="form-grid">
          <label>
            Current password
            <input type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} />
          </label>
          <label>
            New password
            <input type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="At least 10 characters" />
          </label>
          <label>
            Repeat new password
            <input type="password" autoComplete="new-password" value={repeatPassword} onChange={(event) => setRepeatPassword(event.target.value)} />
          </label>
        </div>
        <p className="form-note">Change the seeded password before the site goes live.</p>
      </AdminPanel>
    </>
  );
}

// Change history: what was edited in the panel and when.
function ActivityPanel() {
  const audit = useAuditLog(40);
  return (
    <AdminPanel title="Activity log" subtitle="Every change made in the admin panel" className="table-panel">
      <table>
        <thead><tr><th>When</th><th>Action</th><th>Entity</th><th>Account</th></tr></thead>
        <tbody>
          {(audit.data?.items ?? []).map((entry) => (
            <tr key={entry.id}>
              <td>{formatDate(entry.createdAt)} · {formatRelative(entry.createdAt)}</td>
              <td>{entry.action.replace(/[._]/g, " ")}</td>
              <td>{entry.entity}{entry.entityId ? ` · ${entry.entityId.slice(0, 8)}` : ""}</td>
              <td>{entry.actorEmail || "system"}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {audit.data && audit.data.items.length === 0 ? <p className="chart-empty">Nothing recorded yet.</p> : null}
    </AdminPanel>
  );
}
