import { useEffect, useState } from "react";
import { Loader2, Plus, Save, Trash2 } from "lucide-react";
import { ErrorState, Skeleton, useToast } from "../components/ui";
import { ADMIN_PATH } from "../lib/config";
import { useSaveSettings, useSettings } from "../lib/queries";
import type { Settings } from "../lib/types";
import { AdminPanel, ImageField, PageHeading } from "./components";

// Everything a visitor reads outside product pages lives here: brand copy,
// footer columns, SEO defaults and the public feature toggles.
export function SettingsAdmin() {
  const { data, isLoading, error, refetch } = useSettings();
  const save = useSaveSettings();
  const toast = useToast();
  const [draft, setDraft] = useState<Settings | null>(null);

  useEffect(() => {
    if (data) setDraft(structuredClone(data));
  }, [data]);

  if (isLoading || !draft) return <div className="dashboard"><Skeleton height={300} /></div>;
  if (error) return <div className="dashboard"><ErrorState error={error} onRetry={() => refetch()} /></div>;

  const saveGroup = async (key: keyof Settings) => {
    try {
      await save.mutateAsync({ key, value: draft[key] as unknown as Record<string, unknown> });
      toast("Settings saved");
    } catch (saveError) {
      toast(saveError instanceof Error ? saveError.message : "Save failed", "error");
    }
  };

  const saveAll = async () => {
    for (const key of ["site", "seo", "footer", "features"] as (keyof Settings)[]) {
      await save.mutateAsync({ key, value: draft[key] as unknown as Record<string, unknown> });
    }
    toast("All settings saved");
  };

  return (
    <div className="dashboard">
      <PageHeading title="Settings" text="Brand, SEO defaults, footer and public feature toggles.">
        <button type="button" className="btn primary" onClick={saveAll} disabled={save.isPending}>
          {save.isPending ? <Loader2 size={15} className="spin" /> : <Save size={15} />} Save all
        </button>
      </PageHeading>

      <AdminPanel
        title="Site"
        subtitle="Brand name and shared copy"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("site")}>Save</button>}
      >
        <div className="form-grid">
          <label>Site name<input value={draft.site.name} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, name: event.target.value } })} /></label>
          <label>Tagline<input value={draft.site.tagline} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, tagline: event.target.value } })} /></label>
          <label>Support email<input value={draft.site.supportEmail} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, supportEmail: event.target.value } })} /></label>
          <label>Search placeholder<input value={draft.site.searchPlaceholder} onChange={(event) => setDraft({ ...draft, site: { ...draft.site, searchPlaceholder: event.target.value } })} /></label>
        </div>
      </AdminPanel>

      <AdminPanel
        title="SEO defaults"
        subtitle="Used when a page or product has no override"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("seo")}>Save</button>}
      >
        <div className="form-grid">
          <label>Title template<input value={draft.seo.titleTemplate} onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, titleTemplate: event.target.value } })} placeholder="%s — ToolHub" /></label>
          <label>Default title<input value={draft.seo.defaultTitle} onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, defaultTitle: event.target.value } })} /></label>
          <label className="wide">
            Default description
            <textarea rows={2} value={draft.seo.defaultDescription} onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, defaultDescription: event.target.value } })} />
          </label>
          <label className="wide">
            Keywords
            <input
              value={draft.seo.keywords.join(", ")}
              onChange={(event) => setDraft({ ...draft, seo: { ...draft.seo, keywords: event.target.value.split(",").map((word) => word.trim()).filter(Boolean) } })}
            />
          </label>
          <div className="wide">
            <ImageField
              label="Default OpenGraph image"
              prefix="branding"
              value={draft.seo.ogImage}
              onChange={(url) => setDraft({ ...draft, seo: { ...draft.seo, ogImage: url } })}
            />
          </div>
        </div>
        <p className="form-note">
          sitemap.xml and robots.txt are generated by the server. robots.txt disallows <code>{ADMIN_PATH}</code>, and the panel is
          served with a noindex header.
        </p>
      </AdminPanel>

      <AdminPanel
        title="Footer"
        subtitle="Columns, links and newsletter copy"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("footer")}>Save</button>}
      >
        <div className="form-grid">
          <label className="wide">
            About text
            <textarea rows={2} value={draft.footer.about} onChange={(event) => setDraft({ ...draft, footer: { ...draft.footer, about: event.target.value } })} />
          </label>
          <label className="wide">Copyright<input value={draft.footer.copyright} onChange={(event) => setDraft({ ...draft, footer: { ...draft.footer, copyright: event.target.value } })} /></label>
        </div>

        {draft.footer.columns.map((column, columnIndex) => (
          <div className="footer-column-editor" key={columnIndex}>
            <div className="repeater-row">
              <input
                className="grow"
                value={column.title}
                placeholder="Column title"
                onChange={(event) => {
                  const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, title: event.target.value } : item));
                  setDraft({ ...draft, footer: { ...draft.footer, columns } });
                }}
              />
              <button
                type="button"
                className="icon-btn danger"
                onClick={() => setDraft({ ...draft, footer: { ...draft.footer, columns: draft.footer.columns.filter((_, i) => i !== columnIndex) } })}
                aria-label="Remove column"
              >
                <Trash2 size={13} />
              </button>
            </div>
            {column.links.map((link, linkIndex) => (
              <div className="repeater-row indented" key={linkIndex}>
                <input
                  value={link.label}
                  placeholder="Label"
                  onChange={(event) => {
                    const links = column.links.map((item, i) => (i === linkIndex ? { ...item, label: event.target.value } : item));
                    const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, links } : item));
                    setDraft({ ...draft, footer: { ...draft.footer, columns } });
                  }}
                />
                <input
                  value={link.href}
                  placeholder="/path"
                  onChange={(event) => {
                    const links = column.links.map((item, i) => (i === linkIndex ? { ...item, href: event.target.value } : item));
                    const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, links } : item));
                    setDraft({ ...draft, footer: { ...draft.footer, columns } });
                  }}
                />
                <button
                  type="button"
                  className="icon-btn danger"
                  onClick={() => {
                    const links = column.links.filter((_, i) => i !== linkIndex);
                    const columns = draft.footer.columns.map((item, i) => (i === columnIndex ? { ...item, links } : item));
                    setDraft({ ...draft, footer: { ...draft.footer, columns } });
                  }}
                  aria-label="Remove link"
                >
                  <Trash2 size={13} />
                </button>
              </div>
            ))}
            <button
              type="button"
              className="btn ghost small"
              onClick={() => {
                const columns = draft.footer.columns.map((item, i) =>
                  i === columnIndex ? { ...item, links: [...item.links, { label: "", href: "/" }] } : item
                );
                setDraft({ ...draft, footer: { ...draft.footer, columns } });
              }}
            >
              <Plus size={13} /> Add link
            </button>
          </div>
        ))}

        <button
          type="button"
          className="btn ghost small"
          onClick={() => setDraft({ ...draft, footer: { ...draft.footer, columns: [...draft.footer.columns, { title: "New column", links: [] }] } })}
        >
          <Plus size={13} /> Add column
        </button>
      </AdminPanel>

      <AdminPanel
        title="Public features"
        subtitle="Turn parts of the site on or off"
        action={<button type="button" className="btn ghost small" onClick={() => saveGroup("features")}>Save</button>}
      >
        <div className="switch-row">
          <label className="switch">
            <input
              type="checkbox"
              checked={draft.features.reviewsEnabled}
              onChange={(event) => setDraft({ ...draft, features: { ...draft.features, reviewsEnabled: event.target.checked } })}
            />
            Visitor reviews
          </label>
          <label className="switch">
            <input
              type="checkbox"
              checked={draft.features.newsletterEnabled}
              onChange={(event) => setDraft({ ...draft, features: { ...draft.features, newsletterEnabled: event.target.checked } })}
            />
            Newsletter form
          </label>
          <label className="switch">
            <input
              type="checkbox"
              checked={draft.features.showDownloadCounts}
              onChange={(event) => setDraft({ ...draft, features: { ...draft.features, showDownloadCounts: event.target.checked } })}
            />
            Show download counts
          </label>
        </div>
      </AdminPanel>
    </div>
  );
}
