#!/usr/bin/env bash
# Refreshes the Cloudflare ranges nginx trusts for real-IP restoration, and the
# ufw rules that keep the origin reachable only through Cloudflare.
#
#   sudo ./cloudflare-ips.sh          # nginx ranges only
#   sudo ./cloudflare-ips.sh --ufw    # also rewrite the firewall rules
#
# Cloudflare publishes new ranges occasionally, so run this from cron monthly.
set -euo pipefail

OUT=/etc/nginx/cloudflare-ips.conf
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

fetch() {
  curl -fsS --retry 3 "https://www.cloudflare.com/ips-$1"
}

V4=$(fetch v4)
V6=$(fetch v6)

if [ -z "$V4" ] || [ -z "$V6" ]; then
  echo "Could not download the Cloudflare ranges; keeping the current file." >&2
  exit 1
fi

{
  echo "# Generated by deploy/cloudflare-ips.sh on $(date -u +%F)"
  for range in $V4 $V6; do
    echo "set_real_ip_from $range;"
  done
} > "$TMP"

install -m 0644 "$TMP" "$OUT"
nginx -t && systemctl reload nginx
echo "Wrote $OUT"

if [ "${1:-}" = "--ufw" ]; then
  # Only Cloudflare may reach 80/443, so nobody can bypass the edge by hitting
  # the origin IP directly and forging CF-Connecting-IP.
  ufw --force delete allow 80/tcp  >/dev/null 2>&1 || true
  ufw --force delete allow 443/tcp >/dev/null 2>&1 || true
  while read -r rule; do
    [ -n "$rule" ] && ufw --force delete "$rule" >/dev/null 2>&1 || true
  done < <(ufw status numbered | grep -oE "allow from [0-9a-f.:/]+ to any port (80|443)" || true)

  for range in $V4 $V6; do
    ufw allow from "$range" to any port 80  proto tcp comment "cloudflare" >/dev/null
    ufw allow from "$range" to any port 443 proto tcp comment "cloudflare" >/dev/null
  done
  echo "Firewall now accepts 80/443 from Cloudflare ranges only."
  echo "Make sure SSH stays allowed: ufw status"
fi
