// ISO 3166-1 alpha-2 codes for the countries the catalog reports on, with the
// region used to group them in the analytics dashboard.
export const COUNTRIES = [
  ["US", "United States", "Americas"],
  ["CA", "Canada", "Americas"],
  ["BR", "Brazil", "Americas"],
  ["MX", "Mexico", "Americas"],
  ["AR", "Argentina", "Americas"],
  ["CL", "Chile", "Americas"],
  ["CO", "Colombia", "Americas"],
  ["GB", "United Kingdom", "Europe"],
  ["DE", "Germany", "Europe"],
  ["FR", "France", "Europe"],
  ["ES", "Spain", "Europe"],
  ["IT", "Italy", "Europe"],
  ["NL", "Netherlands", "Europe"],
  ["PL", "Poland", "Europe"],
  ["SE", "Sweden", "Europe"],
  ["NO", "Norway", "Europe"],
  ["FI", "Finland", "Europe"],
  ["DK", "Denmark", "Europe"],
  ["IE", "Ireland", "Europe"],
  ["PT", "Portugal", "Europe"],
  ["CZ", "Czechia", "Europe"],
  ["RO", "Romania", "Europe"],
  ["UA", "Ukraine", "Europe"],
  ["TR", "Turkey", "Europe"],
  ["RU", "Russia", "Europe"],
  ["IN", "India", "Asia"],
  ["ID", "Indonesia", "Asia"],
  ["PH", "Philippines", "Asia"],
  ["VN", "Vietnam", "Asia"],
  ["TH", "Thailand", "Asia"],
  ["MY", "Malaysia", "Asia"],
  ["SG", "Singapore", "Asia"],
  ["JP", "Japan", "Asia"],
  ["KR", "South Korea", "Asia"],
  ["CN", "China", "Asia"],
  ["PK", "Pakistan", "Asia"],
  ["BD", "Bangladesh", "Asia"],
  ["AE", "United Arab Emirates", "Middle East"],
  ["SA", "Saudi Arabia", "Middle East"],
  ["IL", "Israel", "Middle East"],
  ["EG", "Egypt", "Africa"],
  ["NG", "Nigeria", "Africa"],
  ["ZA", "South Africa", "Africa"],
  ["KE", "Kenya", "Africa"],
  ["MA", "Morocco", "Africa"],
  ["AU", "Australia", "Oceania"],
  ["NZ", "New Zealand", "Oceania"]
];

export const COUNTRY_NAMES = Object.fromEntries(COUNTRIES.map(([code, name]) => [code, name]));
export const COUNTRY_REGIONS = Object.fromEntries(COUNTRIES.map(([code, , region]) => [code, region]));
